/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ehongka' at '4/6/16 1:47 PM' with Gradle 2.12
 *
 * @author ehongka, @date 4/6/16 1:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
